menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/wangzhilong110 
    GitHub: https://github.com/stephenwzl
    #Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
